#!/bin/sh

# Script for running gencache via Docker.

if [ ! "$*" ]; then
	echo "usage: $0 <path>"
	echo "Run the gencache tool from EasyRPG to generate index.json."
	exit 1
fi

script_basedir=$(readlink -f "$(dirname "$0")")
if [ -d "$*" ]; then
	target_basedir=$(readlink -f "$*")
else
	target_basedir=$(readlink -f "$(dirname "$*")")
fi

# Build container
docker build -t easyrpg_gencache "$script_basedir"
# Run the command
docker run --rm -v "$target_basedir":/target:rw -u $(id -u):$(id -g) easyrpg_gencache sh -c "cd /target && /easyrpg/bin/gencache"
exit $?
