#!/bin/sh -e

# Script for running convert.sh via Docker.

if [ ! "$*" ]; then
	echo "usage: $0 <path>"
	echo "Recursively converts all audio files under the given path to .ogg."
	exit 1
fi

script_basedir=$(readlink -f "$(dirname "$0")")
if [ -d "$*" ]; then
	target_basedir=$(readlink -f "$*")
else
	target_basedir=$(readlink -f "$(dirname "$*")")
fi

# Check if we can run docker as regular user
if docker ps &>/dev/null; then
	_DOCKER_PREFIX=""
else
	_DOCKER_PREFIX=sudo
fi

# Build container
$_DOCKER_PREFIX docker build -t audioconvert "$script_basedir"
# Run the command
$_DOCKER_PREFIX docker run --rm -v "$target_basedir":/target:rw -u $(id -u):$(id -g) audioconvert "/target"
exit $?
